import { StyleSheet } from 'react-native';

export const colors = {
  bg: '#0b0f17',
  panel: '#121826',
  panel2: '#1a2233',
  border: '#2a3447',
  text: '#e7ecf3',
  muted: '#8a96ad',
  accent: '#5b8def',
  ok: '#4cc38a',
  warn: '#f6c177',
  bad: '#ef6f6c',
};

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.bg, padding: 16 },
  card: {
    backgroundColor: colors.panel,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 14,
    marginBottom: 12,
  },
  h1: { color: colors.text, fontSize: 22, fontWeight: '700', marginBottom: 12 },
  h2: { color: colors.text, fontSize: 17, fontWeight: '600', marginBottom: 8 },
  label: { color: colors.muted, fontSize: 12, textTransform: 'uppercase', marginBottom: 4 },
  value: { color: colors.text, fontSize: 22, fontWeight: '700' },
  text: { color: colors.text, fontSize: 14 },
  muted: { color: colors.muted, fontSize: 13 },
  input: {
    backgroundColor: colors.panel2,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    color: colors.text,
    fontSize: 14,
  },
  primaryButton: {
    backgroundColor: colors.accent,
    borderRadius: 6,
    paddingVertical: 10,
    paddingHorizontal: 14,
    alignItems: 'center',
  },
  primaryText: { color: 'white', fontWeight: '700' },
  ghostButton: {
    borderRadius: 6,
    paddingVertical: 10,
    paddingHorizontal: 14,
    alignItems: 'center',
    borderColor: colors.border,
    borderWidth: 1,
  },
  ghostText: { color: colors.text, fontWeight: '600' },
  dangerButton: {
    borderRadius: 6,
    paddingVertical: 10,
    paddingHorizontal: 14,
    alignItems: 'center',
    borderColor: colors.bad,
    borderWidth: 1,
  },
  dangerText: { color: colors.bad, fontWeight: '600' },
  row: { flexDirection: 'row', gap: 8, alignItems: 'center', flexWrap: 'wrap' },
  rowBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
});
